# Generated by Django 5.1.6 on 2025-03-05 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0002_remove_comment_rating"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cartitem",
            name="order",
        ),
        migrations.AlterField(
            model_name="book",
            name="img",
            field=models.ImageField(upload_to="", verbose_name="Изображение"),
        ),
        migrations.AlterField(
            model_name="book",
            name="type_of_bunding",
            field=models.CharField(
                choices=[("soft", "Мягкий"), ("hard", "Твердый")],
                max_length=64,
                verbose_name="Тип переплета",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="id",
            field=models.AutoField(
                primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
        ),
    ]
