# Generated by Django 5.2.1 on 2025-05-31 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_orderitem_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='customer',
            new_name='created_by',
        ),
        migrations.AddField(
            model_name='order',
            name='city',
            field=models.CharField(max_length=255, null=True, verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='order',
            name='country',
            field=models.CharField(max_length=32, null=True, verbose_name='Страна'),
        ),
        migrations.AddField(
            model_name='order',
            name='first_name',
            field=models.CharField(max_length=50, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='order',
            name='home',
            field=models.CharField(max_length=10, null=True, verbose_name='Дом'),
        ),
        migrations.AddField(
            model_name='order',
            name='last_name',
            field=models.CharField(max_length=50, null=True, verbose_name='Фамилия'),
        ),
        migrations.AddField(
            model_name='order',
            name='state',
            field=models.CharField(blank=True, max_length=255, verbose_name='Область'),
        ),
        migrations.AddField(
            model_name='order',
            name='street',
            field=models.CharField(max_length=255, null=True, verbose_name='Улица'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('card', 'Картой при получении'), ('money', 'Наличыми при получении')], max_length=20, verbose_name='Способ оплаты'),
        ),
        migrations.DeleteModel(
            name='Address',
        ),
    ]
