# Generated by Django 5.1.6 on 2025-03-05 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0004_cartitem_order_alter_order_is_delivered_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartitem",
            name="price",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=50
            ),
        ),
        migrations.AlterField(
            model_name="cartitem",
            name="order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                related_query_name="items",
                to="shop.order",
            ),
        ),
    ]
