# Generated by Django 5.1.6 on 2025-03-07 06:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0007_remove_order_cartitem_cartitem_price_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartitem",
            name="order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="shop.order",
                verbose_name="Заказ",
            ),
        ),
    ]
