# Generated by Django 5.1.6 on 2025-03-19 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0008_cartitem_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="address",
            field=models.CharField(
                default=1, max_length=255, verbose_name="Адрес доставки"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="book",
            name="img",
            field=models.ImageField(
                upload_to="shop\\static\\img", verbose_name="Изображение"
            ),
        ),
    ]
